# Generated by Django 4.2.19 on 2025-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_commentpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
