# Generated by Django 4.2.19 on 2025-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
