# Generated by Django 4.2.19 on 2025-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0006_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='static/image/default.png', upload_to='image/user'),
        ),
    ]
