# Generated by Django 4.2.19 on 2025-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0007_alter_profileuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, default='static/image/default.png', null=True, upload_to='image/user'),
        ),
    ]
