# Generated by Django 4.2.19 on 2025-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0009_alter_profileuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/image'),
        ),
    ]
