# Generated by Django 4.2.19 on 2025-09-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0011_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
