# Generated by Django 4.2.20 on 2025-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/images/download.jfif', upload_to='media/image/user/'),
        ),
    ]
