# Generated by Django 4.2.19 on 2025-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
