# Generated by Django 4.2.19 on 2025-07-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comment_username_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
