# Generated by Django 4.2.19 on 2025-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code_discount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
