# Generated by Django 4.2.19 on 2025-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_discount_code_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='price_discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
