# Generated by Django 4.2.19 on 2025-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_discount_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
