# Generated by Django 4.2.19 on 2025-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_discount_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code_discount',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='price_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
